{% set name = "NeuNorm" %}
{% set version = "1.4.5" %}
{% set sha256 = "fdf60d75ab6688d311e8f62f9b6f1cdbf1586cbdc1a54b33e088386671cda88c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - scipy
    - numpy
    - astropy
    - PIL

test:
  imports:
    - NeuNorm

about:
  home: https://github.com/scikit-beam/NeuNorm
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Neutron Imaging Normalization Library
  description: |
    NeuNorm is an open-source Python library that normalized neutron imaging measurements
  doc_url: http://neunorm.readthedocs.io/
  dev_url: https://github.com/scikit-beam/NeuNorm

extra:
  recipe-maintainers:
    - jeanbilheux
