travis:
  secure:
    BINSTAR_TOKEN: POA9C29rRDrVyH3pgxdcyi9YqM/Cg8LTLSueCTyG5Z5KwH9STotNDFrWMdimAw7+76pjtKMGt/P7wW2aPJjRr5q0ARodyUypJMZADl+j7shse7jaPpRH/2SC4z1az0oKT7F4pu68NM+ra1lMezTyzLmkMuG/F8wbJ/t261H6F9PbASPYsd2MugCKQnhOhxtZ+iqZ5XEonIqD8y3reOz4bVNY6bJWCAMaCG2NdgQFWBrNFvkpq7BnPo2y9bNXWNUOeWymZmFmysuWYiJJP9nPAaaC0vqyLlwp4/3JE9DIKjH4L6JPmvjh3oY2Korsmi0PrDFKvP9RKB12xTBSYXoWY4wXcDHSHv0M+izcU0sTDNmLLUTYeHWIs0fjp15vV5sVLGKtrPpM/3idi2bRZaqaNrdRZK5dSUJEfKxk32M+GJXp9acpRK8rpUO4vq5zNQF7hHLIWrfdC2OfLm8Tud7vFAK1+apzX44Yc0fBWBPPNatbviz+0cUhGei+BAzOH0F2U8PN1Ay+SBrKgG7bAU2mnF8W6xVPCB9QCXFzOi0FowrT8FMfkG41Tcb04CClCgwqdTVMci4pm01uux6eZbr1PeMTckxVbSvBArAHKICfhXwDkB/6/YOoC2iFtV4SA3Y7RwG5WFpcBr+g1yu4+9T9iSSBnfHmM6TYhtbbviVKcfc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
