travis:
  secure:
    BINSTAR_TOKEN: IADmNDSrb5sXviD78BDJnJjCjBJ0PN+yY2aL2/1AYziPKzLH/ZIImb5KgcDUXJN3bwRHsbu6+0dwJcs5NfWCO9o3Z6J/YlYhRKn4XQOTe8ICb2UqrIqnxr/nxiUMXClUF3GZuSCBK2FLcsjUiJvpCC/uKaKmR1ZecCRg7g77mxMkE3YwD6hWQ7NtOR2eflOJhKcXjvlfk35GQSq6nssMwp0Mc+qmUhUIrP9Y7cbAZ/nAvDyKn42iCQ+IqKUy/Bt1lW7X5TNH+ReraL79cUcDUGHqa6N7ODUJTc5KLT7hetowcNPqbUcZefZBiy2dKbuJTyHU6ahdQntruNndKzXPl9ZN5SjbKlXzBQFimtRweCpK/VR0GD6CfhSsYFS8VE44WJtMWGYvGYf6z+iY0Ei8neXgHrUEV71a6zzyJmbAB3yOAGq87iCZKaaw4+DY4W4RMKrcPRis6nU7fgr+wj6JADMIXSuLNOrPVNz7OnV8/GrBoVrsSLVb96BNsg6X/2pgxQSHeaFqAjW8ADExxV1H3PWcW71BD6gGDq7pmJuhh2Jujg5jANZgCil9pbV+8g5rhSeD4jAvCKPuXFt1EiaAN2qgF7CMK19ID5NhIXjAEF1D6u2lYe8VxyEDVpb/A2AUtbelcbbE4wmFUgyG1WZRfPUdRX6y1okm6opZkxrpI4w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
